enum FlightCategory {
  'N/A',
  'No ADS-B Info',
  'Light',
  'Small',
  'Large',
  'High Vortex Large',
  'Heavy',
  'High Performance',
  'Rotorcraft',
  'Glider',
  'Lighter-than-air',
  'Parachutist',
  'Ultralight',
  'Reserved',
  'U.A.V',
  'Trans-atmospheric',
  'Surf. Veh. - Emergency',
  'Surf. Veh. - Service',
  'Point Obstacle',
  'Cluster Obstacle',
  'Line Obstacle',
}
export default FlightCategory;
